// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmosknwegpugqzxctswz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tb3NrbndlZ3B1Z3F6eGN0c3d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjQwODIsImV4cCI6MjA2NzMwMDA4Mn0.UQ0qzud_DutrUxM6pjv5heKy2NZFvvn4ocfBjScgkIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});